# Gitleaks configuration for kanakku project
title = "Gitleaks config for kanakku"

[extend]
# Use the default gitleaks config as base
useDefault = true

# Global allowlists - these apply to all rules
[[allowlists]]
description = "Ignore test files and documentation"
paths = [
  '''.*test.*\.py''',
  '''.*tests/.*''',
  '''.*\.md''',
  '''.*\.rst''',
  '''.*\.txt''',
  '''.*\.yml''',
  '''.*\.yaml''',
  '''.*\.json''',
  '''requirements.*\.txt''',
  '''package.*\.json''',
  '''yarn\.lock''',
  '''.*\.log''',
]

[[allowlists]]
description = "Ignore common false positives"
regexTarget = "match"
regexes = [
  '''(?i)example''',
  '''(?i)sample''',
  '''(?i)dummy''',
  '''(?i)placeholder''',
  '''(?i)test.*key''',
  '''(?i)fake.*secret''',
  '''(?i)mock.*token''',
]

[[allowlists]]
description = "Ignore environment variable examples"
regexTarget = "line"
regexes = [
  '''.*=.*\$\{.*\}.*''',  # Environment variable substitution
  '''.*=.*\<.*\>.*''',    # Placeholder syntax
  '''.*=.*your.*key.*''', # Documentation placeholders
  '''.*=.*change.*me.*''', # Change me placeholders
]

# Custom rules for kanakku-specific patterns
[[rules]]
id = "kanakku-database-url"
description = "Kanakku database connection strings"
regex = '''(?i)(database_url|db_url)\s*=\s*['"](postgresql|mysql|sqlite)://[^'"]*['"]'''
tags = ["database", "connection-string"]

    [[rules.allowlists]]
    description = "Allow test database URLs"
    regexTarget = "match"
    regexes = [
      '''.*test.*''',
      '''.*localhost.*''',
      '''.*127\.0\.0\.1.*''',
    ]

[[rules]]
id = "kanakku-jwt-secret"
description = "JWT secret keys"
regex = '''(?i)(jwt_secret|jwt_secret_key|secret_key)\s*=\s*['"][^'"]{16,}['"]'''
tags = ["jwt", "secret"]

    [[rules.allowlists]]
    description = "Allow development/test JWT secrets"
    regexTarget = "match"
    regexes = [
      '''.*dev.*''',
      '''.*test.*''',
      '''.*local.*''',
      '''.*change.*me.*''',
    ]

[[rules]]
id = "kanakku-api-keys"
description = "API keys and tokens"
regex = '''(?i)(api_key|access_token|auth_token)\s*=\s*['"][^'"]{20,}['"]'''
tags = ["api-key", "token"]

    [[rules.allowlists]]
    description = "Allow test API keys"
    regexTarget = "match"
    regexes = [
      '''.*test.*''',
      '''.*fake.*''',
      '''.*example.*''',
      '''.*dummy.*''',
    ]
