[bank-account-map]
XX1648 = "Assets:Bank:Axis"
XX0907 = "Liabilities:CC:Axis"
XX9005 = "Liabilities:CC:ICICI"

[expense-account-map]
"BAKE HOUSE" = ["Expenses:Food:Restaurant", "Restaurant at Kattangal"]
"SUDEESHKUMA" = ["Expenses:Groceries", "Unni at West Manassery"]
"Jio Prepaid" = ["Expenses:Mobile:Baiju Jio", "FIXME"]
"Kerala Visi" = ["Expenses:Internet:Kerala Vision", "Kerala Vision"]
"ASSAIN CHE" = ["Expenses:Meat", "FIXME"]
"TOP DINES" = ["Expenses:Food:Restaurant", "Restaurant at Mukkam"]
"MANSOORALI" = ["Expenses:Entertainment", "Baston Sports Hub at Kalanthodu"]
"SHANID A" = ["Expenses:Food:Restaurant", "Milma at Kunnamangalam"]
"OASIS EDUPA" = ["Expenses:Education:Book", "Bookstore at Kunnamangalam"]
"Pradeepan C" = ["Expenses:Food:Restaurant", "Chips at Chathamangalam"]
"Mrs.NITH" = ["Expenses:Nithya", "Wife"]
"TRADE L VEN" = ["Expenses:Groceries", "Freshday Hyper Market at Mall of Mukkam"]
"FRESHMART S" = ["Expenses:Groceries", "Fresh Mart Supermarket at Manassery"]
