"""Shared package - imports shared components for easy access"""

from .schemas import (
    BaseResponseSchema,
    CommonFields,
    DateRangeSchema,
    ErrorResponseSchema,
    PaginatedResponseSchema,
    PaginationSchema,
    SearchSchema,
    SuccessResponseSchema,
    validate_amount,
    validate_currency,
    validate_email_format,
    validate_password_strength,
)
from .services import (
    BaseService,
    calculate_pagination_metadata,
    format_api_response,
    format_error_response,
    sanitize_search_term,
    validate_date_range,
)
from .utils import (
    build_search_query,
    calculate_percentage_change,
    clean_text_for_search,
    extract_account_number_from_text,
    format_currency,
    generate_api_key,
    generate_secure_token,
    get_client_ip,
    get_date_range_for_period,
    is_valid_email,
    log_user_action,
    mask_sensitive_data,
    parse_amount_string,
    round_currency,
    sanitize_filename,
    truncate_text,
    validate_date_string,
)

__all__ = [
    # Services
    "BaseService",
    "format_api_response",
    "format_error_response",
    "validate_date_range",
    "sanitize_search_term",
    "calculate_pagination_metadata",
    # Schemas
    "PaginationSchema",
    "DateRangeSchema",
    "SearchSchema",
    "BaseResponseSchema",
    "ErrorResponseSchema",
    "SuccessResponseSchema",
    "PaginatedResponseSchema",
    "CommonFields",
    "validate_currency",
    "validate_amount",
    "validate_email_format",
    "validate_password_strength",
    # Utils
    "generate_secure_token",
    "generate_api_key",
    "sanitize_filename",
    "format_currency",
    "parse_amount_string",
    "validate_date_string",
    "get_date_range_for_period",
    "mask_sensitive_data",
    "extract_account_number_from_text",
    "clean_text_for_search",
    "build_search_query",
    "calculate_percentage_change",
    "round_currency",
    "is_valid_email",
    "truncate_text",
    "get_client_ip",
    "log_user_action",
]
