"""Add EmailConfiguration model

Revision ID: d0f40e38d9f6
Revises:
Create Date: 2025-05-18 23:11:13.570769

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0f40e38d9f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("imap_server", sa.String(length=255), nullable=True),
        sa.Column("imap_port", sa.Integer(), nullable=True),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("app_password", sa.String(length=255), nullable=False),
        sa.Column("polling_interval", sa.String(length=50), nullable=True),
        sa.Column("last_check_time", sa.DateTime(), nullable=True),
        sa.Column("sample_emails", sa.Text(), nullable=True),
        sa.Column("last_processed_email_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_email_configurations")
    # ### end Alembic commands ###
