name: Check formatting with Black

on:
  push:
    paths:
      - 'backend/**.py'
      - '.github/workflows/lint-black.yml'
  pull_request:
    paths:
      - 'backend/**.py'
      - '.github/workflows/lint-black.yml'

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black

      - name: Check formatting with Black
        run: black --check backend/