name: Lint with Ruff

on:
  push:
    paths:
      - 'backend/**.py'
      - '.github/workflows/lint-ruff.yml'
  pull_request:
    paths:
      - 'backend/**.py'
      - '.github/workflows/lint-ruff.yml'

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check backend/ 